"""
Export a trained checkpoint to Roblox-loadable weight files.

Usage (from training/):
    python src/export.py

Outputs:
    training/weights/weights.json   — raw JSON
    training/weights/weights.lua    — Lua table

Important:
- chars is exported as a LIST, not one packed string
- stoi is exported too for debugging
"""

import json
import sys
import torch
from pathlib import Path

WEIGHTS_DIR = Path(__file__).parent.parent / "weights"
CKPT_PATH   = WEIGHTS_DIR / "checkpoint.pt"


def tensor_to_list(t: torch.Tensor) -> list:
    arr = t.detach().float().cpu().numpy()
    if arr.ndim == 1:
        return [float(f"{float(v):.9g}") for v in arr]
    elif arr.ndim == 2:
        return [[float(f"{float(v):.9g}") for v in row] for row in arr]
    elif arr.ndim == 3:
        return [[[float(f"{float(v):.9g}") for v in col] for col in row] for row in arr]
    else:
        raise ValueError(f"Unsupported tensor ndim: {arr.ndim}")


def fmt_float(v: float) -> str:
    return f"{v:.9g}"


def lua_value(obj, indent: int = 0) -> str:
    pad  = "\t" * indent
    pad1 = "\t" * (indent + 1)

    if isinstance(obj, bool):
        return "true" if obj else "false"
    elif isinstance(obj, float) or isinstance(obj, int):
        return fmt_float(float(obj))
    elif isinstance(obj, str):
        escaped = (
            obj.replace("\\", "\\\\")
               .replace('"', '\\"')
               .replace("\n", "\\n")
               .replace("\r", "\\r")
               .replace("\t", "\\t")
               .replace("\0", "\\0")
        )
        return f'"{escaped}"'
    elif isinstance(obj, list):
        if not obj:
            return "{}"
        if isinstance(obj[0], (int, float)):
            inner = ", ".join(fmt_float(float(v)) for v in obj)
            line = "{" + inner + "}"
            if len(line) < 120:
                return line
            lines = [pad1 + fmt_float(float(v)) for v in obj]
            return "{\n" + ",\n".join(lines) + "\n" + pad + "}"
        else:
            rows = [pad1 + lua_value(item, indent + 1) for item in obj]
            return "{\n" + ",\n".join(rows) + "\n" + pad + "}"
    elif isinstance(obj, dict):
        lines = []
        for k, v in obj.items():
            key = f'["{k}"]' if not k.isidentifier() else k
            lines.append(f"{pad1}{key} = {lua_value(v, indent + 1)}")
        return "{\n" + ",\n".join(lines) + "\n" + pad + "}"
    else:
        raise TypeError(f"Cannot convert {type(obj)} to Lua")


def main():
    if not CKPT_PATH.exists():
        sys.exit(f"No checkpoint found at {CKPT_PATH}.\nRun python src/train.py first.")

    print(f"Loading checkpoint from {CKPT_PATH} ...")
    ckpt = torch.load(CKPT_PATH, map_location="cpu", weights_only=True)

    config = ckpt["config"]
    vocab = ckpt["vocab"]
    state = ckpt["model_state"]

    weights_dict: dict[str, list] = {}
    for name, tensor in state.items():
        # Skip causal mask buffer
        if name.endswith(".bias") and tensor.dim() == 4:
            print(f"  Skipping causal mask: {name}")
            continue
        weights_dict[name] = tensor_to_list(tensor)
        shape_str = "x".join(str(s) for s in tensor.shape)
        print(f"  Exported {name:50s} {shape_str}")

    chars_list = vocab["chars"]
    stoi_dict = vocab["stoi"]

    export = {
        "config": config,
        "chars": chars_list,
        "stoi": stoi_dict,
        "weights": weights_dict,
    }

    json_path = WEIGHTS_DIR / "weights.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(export, f, ensure_ascii=False, separators=(",", ":"))
    print(f"\nJSON -> {json_path} ({json_path.stat().st_size // 1024} KB)")

    lua_path = WEIGHTS_DIR / "weights.lua"
    with open(lua_path, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by export.py — do not edit manually\n")
        f.write("-- Paste this file's contents into a Roblox ModuleScript\n\n")
        f.write("return ")
        f.write(lua_value(export))
        f.write("\n")
    print(f"Lua  -> {lua_path} ({lua_path.stat().st_size // 1024} KB)")

    print("\nDone.")
    print("Important: chars is now a Lua/JSON array, not a packed string.")


if __name__ == "__main__":
    main()